### ISSUE TITLE
GATK missing calls convention

### ISSUE THREAD

**Issue by hammer** [sgkit-dev/vcf-zarr-spec#10]
They made a big change and we should probably be aware of it: https://twitter.com/ksamuk/status/1754698562343149936

Blog post from the GATK team https://gatk.broadinstitute.org/hc/en-us/articles/6012243429531-GenotypeGVCFs-and-the-death-of-the-dot

**Comment by hammer** [comment]
More discussion https://github.com/samtools/hts-specs/issues/756

**Comment by tomwhite** [comment]
This has been reverted in the latest GATK release: https://github.com/broadinstitute/gatk/releases/tag/4.6.0.0
