### ISSUE TITLE
Add link to https://sgkit-dev.github.io/bio2zarr/vcf2zarr/overview.html

### ISSUE THREAD

**Issue by hyanwong** [sgkit-dev/vcf-zarr-spec#26]
People coming to this repo might want to know how to make a VCF Zarr file. At the moment the only link in the README is to the top level of SGkit.

**Comment by hyanwong** [comment]
It might also be good to link to the preprint, at https://www.biorxiv.org/content/10.1101/2024.06.11.598241v1

**Comment by jeromekelleher** [comment]
Good call.
